"""Another migration.

Revision ID: 281d5adaecc5
Revises: 15052260daaf
Create Date: 2023-05-10 16:54:37.257050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281d5adaecc5'
down_revision = '15052260daaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_urls', schema=None) as batch_op:
        batch_op.drop_column('visits')

    # ### end Alembic commands ###
